# ========================
# TOMCAT
# ========================
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# ========================
# SPRING
# ========================
logging:
  level:
    org.springframework: ${LOG_LEVEL:INFO} 

spring:
  web:
    resources:
        static-locations: classpath:/launcherDir/,classpath:/public/
    #resources:
     #   static-locations: classpath:/launcherDir/,classpath:/public/
    devtools:
        restart:
            additional-exclude: launcherDir/**

management:
    health:
        probes:
            enabled: true
    endpoint:
        health: 
            show-details: always

# spring:
#     profiles:
#         active: test 

# ========================
# APPLICATION
# ========================   
lucene:
    queryDefaultRecords: ${LUCENE_QUERY_DEFAULT_RECORDS:10}
    queryMaxRecords: ${LUCENE_QUERY_MAX_RECORDS:50}

app:
    myVar: ${VAR:defaultValue}
    searchServiceUrl: ${SEARCH_SERVICE_URL:https://api3.geo.admin.ch/rest/services/api/SearchServer?sr=2056&origins=parcel,address&type=locations&searchText=}
    cantonServiceUrl: ${CANTON_SERVICE_URL:https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1624,616,96&lang=en&layers=all:ch.swisstopo.swissboundaries3d-kanton-flaeche.fill&limit=1&mapExtent=2468000,1068500,2844000,1316500&returnGeometry=false&sr=2056&tolerance=1&geometry=}
    oerebServiceUrls:
      AG: https://api.geo.ag.ch/v2/oereb/
      AI: https://oereb.ai.ch/ktai/wsgi/oereb/
      AR: https://oereb.ar.ch/ktar/wsgi/oereb/
      BE: https://www.oereb2.apps.be.ch/
      BL: https://oereb.geo.bl.ch/
      BS: https://api.oereb.bs.ch/
      FR: https://geo.fr.ch/RDPPF_ws/RdppfSVC.svc/
      GR: https://oereb.geo.gr.ch/oereb/
      JU: https://geo.jura.ch/crdppf_server/
      LU: https://svc.geo.lu.ch/oereb/
      NE: https://sitn.ne.ch/crdppf/
      NW: https://oereb.gis-daten.ch/oereb/
      OW: https://oereb.gis-daten.ch/oereb/
      SG: https://oereb.geo.sg.ch/ktsg/wsgi/oereb/
      SO: https://geo.so.ch/api/oereb/
      TG: https://map.geo.tg.ch/services/oereb/
      TI: https://cloud.geo.ti.ch/oereb2/
      UR: https://prozessor-oereb.ur.ch/oereb/
      VS: https://rdppfvs.geopol.ch/  
      ZG: https://oereb.zg.ch/ors/
      ZH: https://maps.zh.ch/oereb/v2/
      